### PR TITLE
Update runDisposables documentation examples

### LINKED ISSUE #977: Documentation and code do not agree on runDisposables
[According to the code](https://github.com/ember-lifeline/ember-lifeline/blob/master/addon/utils/disposable.ts#L54), runDisposables is deprecated and is not required anymore. This clashes with the [documentation](https://ember-lifeline.github.io/ember-lifeline/docs/run-disposables) where it strongly recommends to use the method. 
I assume that the documentation needs updating to reflect the new situation in the code.

### PR DESCRIPTION
**Pull request by nlfurniss**
Fixes #977.

Dunno how `API.md` works, I can update the numbers of each section if needed.

@scalvert @rwjblue

### CODE REVIEW

**Review by rwjblue — COMMENTED** [review]
`API.md` is built via this script:

https://github.com/ember-lifeline/ember-lifeline/blob/dc3d4fb54f7034bc50a3449f438c75ce565090d8/package.json#L27

And is based on the inline API docs in the individual files.

**Review by scalvert — APPROVED** [review]
Thank you!

**Comment by nlfurniss** [comment]
@rwjblue  running that command decimates that file

**Comment by nlfurniss** [comment]
@rwjblue running that command decimates that file 😬 

```
Table of contents defined sorting of runTask but no documentation with that namepath was found
Table of contents defined sorting of scheduleTask but no documentation with that namepath was found
Table of contents defined sorting of throttleTask but no documentation with that namepath was found
Table of contents defined sorting of cancelTask but no documentation with that namepath was found
Table of contents defined sorting of debounceTask but no documentation with that namepath was found
Table of contents defined sorting of cancelDebounce but no documentation with that namepath was found
Table of contents defined sorting of pollTask but no documentation with that namepath was found
Table of contents defined sorting of cancelPoll but no documentation with that namepath was found
Table of contents defined sorting of setShouldPoll but no documentation with that namepath was found
Table of contents defined sorting of addEventListener but no documentation with that namepath was found
Table of contents defined sorting of removeEventListener but no documentation with that namepath was found
Table of contents defined sorting of registerDisposable but no documentation with that namepath was found
Table of contents defined sorting of runDisposables but no documentation with that namepath was found
Table of contents defined sorting of DisposableMixin but no documentation with that namepath was found
Table of contents defined sorting of ContextBoundEventListenersMixin but no documentation with that namepath was found
Table of contents defined sorting of ContextBoundTasksMixin but no documentation with that namepath was found
Table of contents defined sorting of pollTaskFor but no documentation with that namepath was found
Table of contents defined sorting of setupLifelineValidation but no documentation with that namepath was found
```

**Comment by scalvert** [comment]
Thanks, @nlfurniss. This was addressed in another PR.

**Pull request closed without merging**
